# Generated by Django 5.0.4 on 2024-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('GBP(£)', 'British Pound'), ('USD($)', 'US Dollar'), ('EUR(€)', 'Euro')], max_length=15, null=True),
        ),
    ]
